# Generated by Django 4.0.5 on 2022-06-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('dias', models.IntegerField()),
                ('fecha_partida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('precio_publico', models.FloatField()),
                ('costo', models.FloatField()),
                ('oferta', models.BooleanField()),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
