# Generated by Django 4.0.5 on 2022-06-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='Image_Set_1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='paquete',
            name='Image_Set_2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
